In [ ]:
import pandas
import os

# This query represents dataset "Procedures_For_Cohort_Dataset" for domain "procedure" and was generated for All of Us Registered Tier Dataset v7
dataset_05338488_procedure_sql = """
    SELECT
        procedure.person_id,
        procedure.procedure_concept_id,
        p_standard_concept.concept_name as standard_concept_name,
        p_standard_concept.concept_code as standard_concept_code,
        p_standard_concept.vocabulary_id as standard_vocabulary,
        procedure.procedure_datetime,
        procedure.procedure_type_concept_id,
        p_type.concept_name as procedure_type_concept_name,
        procedure.modifier_concept_id,
        p_modifier.concept_name as modifier_concept_name,
        procedure.quantity,
        procedure.visit_occurrence_id,
        p_visit.concept_name as visit_occurrence_concept_name,
        procedure.procedure_source_value,
        procedure.procedure_source_concept_id,
        p_source_concept.concept_name as source_concept_name,
        p_source_concept.concept_code as source_concept_code,
        p_source_concept.vocabulary_id as source_vocabulary,
        procedure.modifier_source_value 
    FROM
        ( SELECT
            * 
        FROM
            `""" + os.environ["WORKSPACE_CDR"] + """.procedure_occurrence` procedure 
        WHERE
            (
                procedure_concept_id IN  (
                    SELECT
                        DISTINCT c.concept_id 
                    FROM
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                    JOIN
                        (
                            select
                                cast(cr.id as string) as id 
                            FROM
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                            WHERE
                                concept_id IN (
                                    1314331, 2617204, 2617208, 2617223, 2720580, 2721530, 3047860, 36675054, 36714147, 37204303, 37204304, 37396227, 4000738, 4001217, 4002365, 4002733, 4004516, 4010109, 4012185, 4012907, 4013636, 4016388, 4017459, 40217302, 4024612, 4027403, 4028902, 4028908, 4028909, 4029205, 40295754, 4029698, 4030028, 4030654, 4030660, 4031967, 4032237, 4032251, 4032254, 4032257, 4036803, 4037672, 4039376, 4040390, 4040391, 4040392, 4040393, 4040395, 4040396, 4040400, 4040551, 4040556, 4040559, 4040561, 4040563, 4040721, 4041261, 4041263, 4041982, 4042150, 4042330, 4042486, 4042493, 4042504, 4042516, 4042641, 4042642, 4042645, 4042646, 4042650, 4042660, 4042673, 4042677, 4042678, 4042815, 4043017, 4043018, 4043019, 4043022, 4043023, 4043025, 4043028, 4043161, 4043176, 4043178, 4043179, 4043182, 4043197, 4043334, 4043336, 4044012, 4044875, 4044887, 4044900, 4045893, 4045900, 4047347, 40480674, 40480925, 40481382, 40481384, 40481878, 40482428, 4048375, 40487842, 4052492, 4061009, 4063521, 4064522, 4065062, 4067285, 4072499, 4073050, 4073623, 4075084, 4075966, 4077953, 4078442, 4078460, 4079711, 4088217, 4093436, 4100357, 4104795, 4105895, 4108616, 4109665, 4111522, 4111529, 4111534, 4112892, 4117767, 4118601, 4121315, 4124406, 4125501, 4129747, 4132623, 4132648, 4132855, 4133169, 4133312, 4134148, 4134423, 4134598, 4135174, 4138127, 4139262, 4141759, 4144375, 4145308, 4155790, 4155793, 4158570, 4159949, 4160360, 4160550, 4162054, 4163951, 4164278, 4168709, 4171700, 4172515, 4172654, 4176642, 4176720, 4177094, 4178367, 4179713, 4180004, 4180627, 4180642, 4180653, 4180938, 4180941, 4181192, 4181193, 4181322, 4181638, 4181966, 4185115, 4185623, 4189705, 4190496, 4190759, 4194672, 4196582, 4196958, 4201944, 4202517, 4202832, 4208079, 4211641, 4213297, 4214115, 4216752, 4221994, 4229604, 4230374, 4230911, 4231758, 4233946, 4237320, 4237321, 4239679, 4240345, 4241075, 4243910, 4247168, 4248675, 4249893, 4250598, 42536500, 4254477, 4254480, 4258374, 4261206, 4263508, 4264477, 4266234, 4268628, 4270484, 4279903, 4287856, 4293032, 4293902, 4297090, 4299523, 4299602, 4300244, 4300757, 4301351, 4302532, 4304358, 4306074, 4306780, 4310912, 4311405, 4313306, 4313889, 4314450, 4324693, 4326426, 4327748, 43531071, 43531072, 45773385, 45890623, 46272569, 704057
                                ) 
                                AND full_text LIKE '%_rank1]%'
                        ) a 
                            ON (
                                c.path LIKE CONCAT('%.',
                            a.id,
                            '.%') 
                            OR c.path LIKE CONCAT('%.',
                            a.id) 
                            OR c.path LIKE CONCAT(a.id,
                            '.%') 
                            OR c.path = a.id) 
                        WHERE
                            is_standard = 1 
                            AND is_selectable = 1
                        )
                )  
                AND (
                    procedure.PERSON_ID IN (
                        SELECT
                            distinct person_id  
                        FROM
                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                        WHERE
                            cb_search_person.person_id IN (
                                SELECT
                                    criteria.person_id 
                                FROM
                                    (SELECT
                                        DISTINCT person_id,
                                        entry_date,
                                        concept_id 
                                    FROM
                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                    WHERE
                                        (
                                            concept_id IN (
                                                SELECT
                                                    DISTINCT ca.descendant_id 
                                                FROM
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria_ancestor` ca 
                                                JOIN
                                                    (
                                                        select
                                                            distinct c.concept_id 
                                                        FROM
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                        JOIN
                                                            (
                                                                select
                                                                    cast(cr.id as string) as id 
                                                                FROM
                                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                WHERE
                                                                    concept_id IN (21604254) 
                                                                    AND full_text LIKE '%_rank1]%'
                                                            ) a 
                                                                ON (
                                                                    c.path LIKE CONCAT('%.',
                                                                a.id,
                                                                '.%') 
                                                                OR c.path LIKE CONCAT('%.',
                                                                a.id) 
                                                                OR c.path LIKE CONCAT(a.id,
                                                                '.%') 
                                                                OR c.path = a.id) 
                                                            WHERE
                                                                is_standard = 1 
                                                                AND is_selectable = 1
                                                            ) b 
                                                                ON (
                                                                    ca.ancestor_id = b.concept_id
                                                                )
                                                        ) 
                                                        AND is_standard = 1
                                                    )
                                            ) criteria 
                                        ) 
                                        AND cb_search_person.person_id NOT IN (
                                            SELECT
                                                criteria.person_id 
                                        FROM
                                            (SELECT
                                                DISTINCT person_id,
                                                entry_date,
                                                concept_id 
                                            FROM
                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                            WHERE
                                                (
                                                    concept_id IN (
                                                        SELECT
                                                            DISTINCT c.concept_id 
                                                        FROM
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                        JOIN
                                                            (
                                                                select
                                                                    cast(cr.id as string) as id 
                                                                FROM
                                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                WHERE
                                                                    concept_id IN (40493428, 252840, 4092524, 4178964, 76349, 4177243, 4313083, 4241905, 46273652, 196925, 4180791, 436045, 200962, 4091466, 4162860, 4294416, 4092212, 444411, 4154630, 442139, 4309225, 4298032, 40650479, 197807, 4091465, 40490994, 4216273, 133424, 4247726, 4247822, 4181483, 4162994, 4309851, 436671, 4180780, 4300555, 4160780, 4180910, 4247238, 4155297, 4178971, 443568, 75210, 442183, 40492021, 78987, 443388, 195483, 4155285, 4181488, 25189, 4180902, 36676291, 376918, 4297666, 4157332, 40488919, 380661, 256633, 133711, 200348, 4174593, 433143, 4178977, 4178959, 443387, 40480128, 432263, 4312698, 4315805, 4112853, 4297185, 4181333, 442181, 46270738, 4178974, 4246450, 442131, 443391, 444410, 137809, 4181330, 4313916, 40487047, 192581, 4314047, 4092217, 4181351, 37397344, 4112745, 257503, 438693, 139750, 4181338, 198091, 436357, 196359, 432257, 4246451, 258375, 200052, 40488964, 256646, 436353, 438094, 4312023, 31509, 201238, 37310458, 4095312, 138996, 4162253, 378087, 435484, 374874, 36684472, 4314071, 4312288, 261514, 4181332, 44806773, 196360, 4188544, 4298026, 443392, 4295624, 432845, 45769720, 197507, 4233629, 4241917, 199754, 4160276, 440649, 443588, 4089655, 4092511, 439751, 432837, 4095740, 197808, 4162251, 200051, 4310566, 4187850, 26052, 4187849, 4311637, 4246017, 440658, 4247719, 4312685, 4241904, 4181480, 4311342, 4116084, 4111921, 36683531, 441805, 4298028, 437498, 4054503, 4298033, 192568, 4246127, 4312022, 4081044, 197500, 373425, 4338758, 443398, 376647, 4308621, 198988, 40491001, 40492037, 40490993, 4180793, 4181484, 4247338, 4297665, 441515, 74582, 442132, 261236, 4188545, 4180790, 4247331, 133726, 433716, 258369, 136917, 440345, 200959, 320342, 434298, 4334322, 4181350, 40492932, 4178968, 198700, 380055, 440956, 4111776, 4311619, 4247836, 4155171, 432833, 4111805, 433435, 201519, 438386, 4178976, 192855, 4157457, 75512, 4311617, 4157456, 24897, 45770892, 4187848, 80045, 4116241, 45768522, 4311499, 72266, 255507, 193144, 30346, 4315806, 443561, 28083, 4001666, 4089665, 4089756, 439404, 435755, 42536893, 4312944, 443390, 40493020, 4187851, 441233, 4248061, 4247357, 4157454, 4313482, 438699, 318096, 4112974, 432254, 4158563, 4091464, 436635, 198985, 40482750, 254591, 4181343, 197804, 4151250, 40487143, 443386, 46270513, 4157449, 4181354, 4181339, 133147, 443389, 4092382, 45757101, 4313634, 4307263, 4092512, 194589, 253717, 136354, 764225, 195513, 4153882, 4157331, 4214901, 4181477) 
                                                                    AND full_text LIKE '%_rank1]%'
                                                            ) a 
                                                                ON (
                                                                    c.path LIKE CONCAT('%.',
                                                                a.id,
                                                                '.%') 
                                                                OR c.path LIKE CONCAT('%.',
                                                                a.id) 
                                                                OR c.path LIKE CONCAT(a.id,
                                                                '.%') 
                                                                OR c.path = a.id) 
                                                            WHERE
                                                                is_standard = 1 
                                                                AND is_selectable = 1
                                                            ) 
                                                            AND is_standard = 1 
                                                    )
                                                ) criteria 
                                            ) ))
                                ) procedure 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_standard_concept 
                                    ON procedure.procedure_concept_id = p_standard_concept.concept_id 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_type 
                                    ON procedure.procedure_type_concept_id = p_type.concept_id 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_modifier 
                                    ON procedure.modifier_concept_id = p_modifier.concept_id 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.visit_occurrence` v 
                                    ON procedure.visit_occurrence_id = v.visit_occurrence_id 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_visit 
                                    ON v.visit_concept_id = p_visit.concept_id 
                            LEFT JOIN
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_source_concept 
                                    ON procedure.procedure_source_concept_id = p_source_concept.concept_id"""

dataset_05338488_procedure_df = pandas.read_gbq(
    dataset_05338488_procedure_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook")

dataset_05338488_procedure_df.head(5)